#server:
#  port: 8080
#
#spring:
#  mvc:
#    #JSP配置
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
#  datasource:
#    url: jdbc:mysql://localhost:3306/school?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: 12345678
#    driver-class-name: com.mysql.cj.jdbc.Driver